ports:
  # Shopware server
  - port: 8000
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: ignore

tasks:
  - init: >
      cd production &&
      docker-compose up -d &&
      composer install &&
      bin/console system:setup &&
      bin/console system:install --create-database --basic-setup